"""
This file contains the default values for the sensors of the ego vehicle.
"""

CAMERA_ARGUMENTS = {
    "image_height": 512,  # Height of Image in px for all image outputs
    "image_width": 768,  # Width of Image in px for all image outputs
    "camera_fov": 90.0,  # Field of view for all image outputs
}

LIDAR_ARGUMENTS = {
    "range": 100.0,  # Maximum distance to measure/ray-cast in meters
    "upper_fov": 15.0,  # Angle in degrees of the highest laser
    "lower_fov": -25.0,  # Angle in degrees of the lowest laser
    "channels": 64,  # Number of lasers for the LIDAR
    "rotation_frequency": 200.0,
    # highly advised to not change this parameter. Fixed Delta Time steps for synchronous mode needs to be adjusted as well
    "points_per_second": 1000000,  # Points generated by all lasers per second
    "noise_stddev": 0.1,
    "dropoff_rate": 0.0,  # General proportion of points that are random dropped
    "dropoff_intensity_limit": 0.0,  # For the intensity based drop-off, the threshold intensity value above which no points are dropped
    "dropoff_zero_intensity": 0.0,  # For the intensity based drop-off, the probability of each point with zero intensity being dropped
}
